### ISSUE TITLE
Only Loading...... is still in the magicMirror

### ISSUE THREAD

**Issue by HeisemerBub** [0m4r/MMM-SoccerLiveScore#14] opened 2024-09-13 13:26 UTC
Hello, your module is great and worked very well until yesterday, but now all of a sudden it only says “Loading...” in the MagicMirror :-(
I have not changed anything in the config. Could you please have a look in your module to see what might be wrong?

Thank you very much...here is an excerpt from my config showing how I integrated the module
![Image 001](https://github.com/user-attachments/assets/92ea3ceb-e749-45b1-bdac-026ec35f2c92)

`{
		module: 'MMM-SoccerLiveScore',
		position: 'top_left',
		header: 'Fussball',
		config: {
			leagues: [35, 44, 491],
			showNames: true,
			showLogos: true,
			displayTime: 60 * 1000,
			showTables: true,
			language: 'de',
		}
		},`

**Comment by Domo82** [comment] 2024-09-13 15:51
please see https://github.com/0m4r/MMM-SoccerLiveScore/issues/13

**Comment by HeisemerBub** [comment] 2024-09-13 16:45
unfortunately no solution has been found yet :-(

**Comment by 0m4r** [comment] 2024-09-13 18:37
> Hello, your module is great and worked very well until yesterday, but now all of a sudden it only says “Loading...” in the MagicMirror :-( I have not changed anything in the config. Could you please have a look in your module to see what might be wrong?
> 
> Thank you very much...here is an excerpt from my config showing how I integrated the module ![Image 001](https://private-user-images.githubusercontent.com/74556952/367312611-92ea3ceb-e749-45b1-bdac-026ec35f2c92.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTI4MDksIm5iZiI6MTcyNjI1MjUwOSwicGF0aCI6Ii83NDU1Njk1Mi8zNjczMTI2MTEtOTJlYTNjZWItZTc0OS00NWIxLWJkYWMtMDI2ZWMzNWYyYzkyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE4MzUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NmVmN2EwOGU4NjA5OWRhNzJlYmMxYWFhNDYyMjkxZjk5MzlkYTIxYjg0NGIxMjUzZDQzMTc1NDZmNGU1YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3bgK7R8HgXl7NHkxYIqlLqVMLL6tEDoW-HieZdcuxss)
> 
> `{ module: 'MMM-SoccerLiveScore', position: 'top_left', header: 'Fussball', config: { leagues: [35, 44, 491], showNames: true, showLogos: true, displayTime: 60 * 1000, showTables: true, language: 'de', } },`

hi @Domo82 thanks for reporting this.
The APIs used by this module are not available anymore.
I am trying to use a different solution by implementing other APIs, but as I only do this in my spare time, it may take a while.

I will close this as a duplicate of #13, please follow the updates on that other thread.

**Closed as completed by 0m4r** 2024-09-13 18:37 UTC
Labels: bug, duplicate
